DROP TABLE IF EXISTS CONTENT;
  
CREATE TABLE CONTENT (
  id INT PRIMARY KEY,
  creator VARCHAR(250) NOT NULL,
  title VARCHAR(250) NOT NULL,
  journal VARCHAR(250) NOT NULL,
  summary VARCHAR(250) NOT NULL
);

CREATE TABLE BUNDLE (
  id INT PRIMARY KEY,
  creator VARCHAR(250) NOT NULL,
  title VARCHAR(250) NOT NULL
);